# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlist1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtoPlaylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_added', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('times_added', models.IntegerField(blank=True, default=0, null=True)),
                ('added_by', models.ManyToManyField(related_name='added', to='playlist1.User')),
            ],
        ),
        migrations.AddField(
            model_name='addtoplaylist',
            name='song_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_song', to='playlist2.Song'),
        ),
        migrations.AddField(
            model_name='addtoplaylist',
            name='user_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_user', to='playlist1.User'),
        ),
    ]
