# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bright_ideas1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.TextField()),
                ('times_liked', models.IntegerField(default=0)),
                ('adds_idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by', to='bright_ideas1.User')),
                ('likes_idea', models.ManyToManyField(related_name='liked_by', to='bright_ideas1.User')),
            ],
        ),
    ]
